logging:
  level:
    com.amadeus: TRACE
    com.backfunctionimpl.travel.config.AmadeusClient: TRACE
    com.backfunctionimpl.travel.travelFlight.service: DEBUG
    root: INFO
    org.springframework: DEBUG
    org.springframework.core.env: TRACE
    org.springframework.boot.autoconfigure: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.reactive: DEBUG
    com.backfunctionimpl: TRACE
    io.github.cdimascio.dotenv: DEBUG
    org.hibernate: DEBUG
    com.zaxxer.hikari: DEBUG

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-airflow.c9ey8eai2kkp.ap-northeast-2.rds.amazonaws.com:3306/airflow?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME:default-username}
    password: ${DB_PASSWORD:default-password}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: "http://localhost:8081/login/oauth2/code/google"
            scope:
              - email
              - profile
          naver:
            client-id: ${NAVER_CLIENT_ID}
            client-secret: ${NAVER_CLIENT_SECRET}
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/login/oauth2/code/naver
            scope:
              - name
              - email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 86400 # 24시간
      # password: your_redis_password (필요시 주석 해제)

  cache:
    type: redis

fastapi:
  api-key: my_unique_secure_key_12345

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

google:
  maps-key: ${GOOGLE_MAPS_API_KEY}

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    stack:
      auto: false

amadeus:
  client-id: ${AMADEUS_CLIENT_ID}
  client-secret: ${AMADEUS_CLIENT_SECRET}
  api:
    base-url: https://test.api.amadeus.com

kakaopay:
  secret-key: ${KAKAOPAY_SECRET_KEY}
  cid: TC0ONETIME
  # 카카오페이 API용 URL
  ready-url: https://open-api.kakaopay.com/online/v1/payment/ready
  approve-api-url: https://open-api.kakaopay.com/online/v1/payment/approve
  cancel-api-url: https://open-api.kakaopay.com/online/v1/payment/cancel
  order-api-url: https://open-api.kakaopay.com/online/v1/payment/order  # 상태 확인용
  # 사용자 redirect용 URL
  approval-url: http://13.125.2.46/payment/success
  cancel-url: http://13.125.2.46/payment/cancel
  fail-url: http://13.125.2.46/payment/fail

application:
  bucket:
    name: joo-legend
  spring:
    servlet:
      multipart:
        enabled: true
        max-file-size: 10MB
        max-request-size: 50MB
    file:
      upload-dir: /uploads

